plugins { id 'com.android.application' }

android {
    namespace 'com.francus.pomodors'
    compileSdk 36

    defaultConfig {
        applicationId 'com.francus.pomodors'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
    }
}
